### ISSUE TITLE
Make tests more robust for in-tree builds

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kynesim/kbus#57]
```
Here's a patch which makes the kbus tests more robust for in-tree builds - it 
uses modprobe instead of insmod, and if it wasn't able to modprobe but there 
was a /dev/kbus0 then it doesn't try to rmmod it afterwards (covering the 
monolithic case).

I haven't committed it as it may be controversial. Tibs, what do you think?
```

Original issue reported on code.google.com by `crazys...@gmail.com` on 26 Jan 2011 at 11:51

Attachments:
- [modprobe-not-insmod](https://storage.googleapis.com/google-code-attachments/kbus/issue-57/comment-0/modprobe-not-insmod)

**Comment by RMJ10** [comment]
The attachment is lost in the depths of internet history now, so I'm closing this.
